Update new legendary NUS Hackers President name
nushackers/nushackers-site pull request #413
Opened 2021-05-20 03:25 UTC by chrisgzf

2021-05-21 18:35 UTC, angelsl approved these changes

2021-05-22 07:45 UTC, jethrokuan approved these changes

2021-05-22 10:42 UTC, sushinoya approved these changes
All hail president jingyen

2021-05-23 07:55 UTC, JingYenLoh requested changes

2021-05-23 07:55 UTC, JingYenLoh commented on data/coreteam_members.yml
> +
Remove whitespace

2021-05-23 07:55 UTC, JingYenLoh commented on data/coreteam_members.yml
> +
Remove whitespace

2021-05-23 07:56 UTC, merged